name: Test

on:
  push:
    branches: [main]
  pull_request_target:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
        # Settings - Secrets and variables - Actions - New repository secret GITLAB_TOKEN
        # Settings - Secrets and variables - Dependabot  - New repository secret GITLAB_TOKEN
        GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        GITLAB_BASE_URL: https://gitlab.com
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          check-latest: true

      - name: Install binary
        run: go install

      - name: Smoke tests
        run: |
          import-gitlab-commits -h
          import-gitlab-commits --help

      - name: Unit tests
        run: go test -v -count=1 -race -shuffle=on -cover ./...

      - name: Integration tests
        run: go test -tags=integration -run=TestGitLab -shuffle=on -count=1 -race -v ./...
